Django_Level_Four/pro_four/app_four/urls.py
from django.urls import path
from . import views

# Allow Template Tagging by including the 'app_name' variable
app_name = 'app_four'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

Django_Level_Four/pro_four/pro_four/urls.py
from django.contrib import admin
from django.urls import path, include
from app_four import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('app_four/', include('app_four.urls')),
]

Django_Level_Four/pro_four/app_four/models.py
from django.db import models

# Create your models here.

Django_Level_Four/pro_four/app_four/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'app_four/index.html', context=context_dict)

def other(request):
    return render(request, 'app_four/other.html')

def relative(request):
    return render(request, 'app_four/relative_url_templates.html')

Django_Level_Four/pro_four/templates/app_four/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'index' %}" class="navbar-brand">BRAND</a></li>
          <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
          <li><a href="{% url 'app_four:other' %}" class="navbar-link">Other</a></li>
        </ul>

      </div>

    </nav>

    <div class="container">
      {% block body_block %}
      <p>Here is some text that I only want to hold on the 'base.html' page</p>
      {% endblock %}
    </div>

  </body>
</html>

Django_Level_Four/pro_four/templates/app_four/index.html
<!DOCTYPE html>
{% extends "app_four/base.html" %}
{% load my_extras %}
  {% block body_block %}
    <h1>Welcome to Index</h1>
    <h2>{{ text | cut_func:'world' }}</h2>
    <h2>{{ number | add:"99" }}</h2>
  {% endblock %}

Django_Level_Four/pro_four/templates/app_four/other.html
<!DOCTYPE html>
{% extends "app_four/base.html" %}
  {% block body_block %}
    <h1>Welcome to the Other page</h1>
    <h2>This is an example of template inheritance</h2>
  {% endblock %}

Django_Level_Four/pro_four/templates/app_four/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative URL templates</h1>
    <a href="{% url 'app_four:other' %}">The Other Page</a>
    <p></p>
    <a href="{% url 'admin:index' %}">Admin Page</a>
    <p></p>
    <a href="{% url 'index' %}">Index Link</a>
  </body>
</html>