Advanced_Section/CBVs/advbv/advbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('basic_app/', include('basic_app.urls', namespace='basic_app')),
]

Advanced_Section/CBVs/advbv/basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    # path('detail/', views.SchoolDetailView.as_view(), name='detail'),
]

Advanced_Section/CBVs/advbv/basic_app/models.py
from django.db import models

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    princpal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete='CASCADE')

    def __str__(self):
        return self.name

Advanced_Section/CBVs/advbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView
from . import models

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'BASIC INJECTION!'
        return context

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_details.html'

Advanced_Section/CBVs/advbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
        <li><a href="#"></a></li>
      </ul>

    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

Advanced_Section/CBVs/advbv/basic_app/templates/basic_app/school_details.html
{% extends 'basic_app/basic_app_base.html' %}
{% block bodyblock %}

<div class="jumbotron">
  <h1>Welcome to the school detail page!</h1>
    <h2>School Details!</h2>
    <p>Name: {{ school_detail.name }}</p>
    <p>Principal: {{ school_detail.principal }}</p>
    <p>Location: {{ school_detail.location }}</p>
</div>

{% endblock %}

Advanced_Section/CBVs/advbv/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}
{% block bodyblock %}

<h1>Welcome to a list of all the schools!</h1>
  <!-- <ol>
    {% for school in schools %}
      <h2><li>{{ school.name }}</li></h2>
    {% endfor %}
  </ol> -->

{% endblock %}